//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mvcshopping.EDM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblcat
    {
        public decimal cat_id { get; set; }
        public string cat_name { get; set; }
        public string cat_desc { get; set; }
    }
}
